# Generated by Django 5.2.6 on 2025-10-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.IntegerField(auto_created=True)),
                ('task', models.CharField(max_length=700)),
            ],
            options={
                'ordering': ('-tag',),
            },
        ),
        migrations.DeleteModel(
            name='SignupForm',
        ),
    ]
