# Generated by Django 5.2.6 on 2025-10-07 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_delete_signupform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('-date_time',)},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='tag',
        ),
        migrations.AddField(
            model_name='todo',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
